### ISSUE TITLE
Is it possible to add the option use syntax highlighting without pretty-printing feature?

### ISSUE THREAD

**Issue by Rinat-Suleimanov** [skjolber/logback-logstash-syntax-highlighting-decorators#10]
Hi, thanks for the library. 
Did not find the option to turn off pretty printer for the `SyntaxHighlightingDecorator`
Can you please add it or point me to the right place if I just missed it.

**Comment by skjolber** [comment]
Hi @Rinat-Suleimanov, sorry for the slow response, but yes, it is now possible to disable pretty-printing (technically disabling pretty indent + newline).
