### ISSUE TITLE
Clarification on Usage: logs without colors after adding only the appender

### ISSUE THREAD

**Issue by lackovic** [skjolber/logback-logstash-syntax-highlighting-decorators#17]
I added the `appender` mentioned in the [Usage section of the README](https://github.com/skjolber/logback-logstash-syntax-highlighting-decorators#usage) to `src/main/resources/logback-json.xml` but when I run my application I see all my logs still without colors.

Can you please clarify how to use [JsonGeneratorDecorator](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/decorate/JsonGeneratorDecorator.java)?

**Comment by lackovic** [comment]
Instead of adding the whole `appender` I extracted its `encoder` and added it to the pre-existing `appender` in my `logback-json.xml`:
```xml
<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
        <jsonGeneratorDecorator class="net.logstash.logback.decorate.PrettyPrintingJsonGeneratorDecorator"/>
    </encoder>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
        <!-- add pretty-printing and syntax highlighting for testing -->
        <jsonGeneratorDecorator class="com.github.skjolber.decorators.SyntaxHighlightingDecorator"/>
    </encoder>
</appender>
```

I can see colors now, but all the logs, regardless of the level, are red:
![2022-04-15_112518](https://user-images.githubusercontent.com/1663053/163546105-328df8da-c9a5-4cfe-8c7c-29f8e430e1ab.png)
Any idea how to fix that? I.e. how can I have different colors for different logging levels?

**Comment by lackovic** [comment]
I came to the conclusion that red must be the default color. Following the [Custom colors](https://github.com/skjolber/logback-logstash-syntax-highlighting-decorators#custom-colors) section in the README I have added the following decorators to my `LogstashEncoder`:
```xml
<jsonGeneratorDecorator class="com.github.skjolber.decorators.SyntaxHighlightingDecorator">
    <syntaxHighlighterFactory class="com.github.skjolber.decorators.factory.ConfigurableSyntaxHighlighterFactory">
        <stringValue>cyan</stringValue>
        <numberValue>highIntensity green</numberValue>
        <fieldName>highIntensity blue</fieldName>
        <binaryValue>yellowBackground</binaryValue>
        <booleanValue>cyan</booleanValue>
        <nullValue>black</nullValue>
        <curlyBrackets>highIntensity yellow</curlyBrackets>
        <squareBrackets>highIntensity yellow</squareBrackets>
        <colon>white</colon>
        <whitespace>green</whitespace>
        <comma>white</comma>
    </syntaxHighlighterFactory>
    <syntaxHighlighterFactory class="com.github.skjolber.decorators.factory.LogLevelSyntaxHighlighterFactory">
        <level>
            <info>green</info>
            <warning>yellow</warning>
            <error>red</error>
            <debug>magenta</debug>
        </level>
        <message>highIntensity white</message>
    </syntaxHighlighterFactory>
</jsonGeneratorDecorator>
```
which produces the following colorized output:
![2022-04-15_120430](https://user-images.githubusercontent.com/1663053/163551558-45f96522-c9d9-41b2-a2b9-b8041181114c.png)

The color of the strings are still red, despite the `<stringValue>cyan</stringValue>` in my configuration. Anybody knows why?

**Comment by skjolber** [comment]
@lackovic red is indeed a default color, whereas you could set a default ansi value as well. I guess I'll nuke these use of default colors.

**Comment by skjolber** [comment]
@lackovic see latest release, also using one syntaxHighlighterFactory (`LogLevelSyntaxHighlighterFactory`) should be enough.
