### ISSUE TITLE
1 issue and 1 feature request

### ISSUE THREAD

**Issue by likeme** [skjolber/logback-logstash-syntax-highlighting-decorators#22]
Currently there is one issue in this that default colors of level no matter whether its info, debug, error its all red. Which will be  wrong for me. Is there any way to make if default none or disable all the default attributes (similar to prettyPrint false).

There is one more change I am facing that if I want my message color to be according to level, then is there any way to achieve it?

**Comment by skjolber** [comment]
@likeme sorry for the slow response. 

About the level color, why do you have to use the default?
